import { createRoot } from 'react-dom/client'
import './styles.css'
import { App } from './App'
import { useState } from 'react'
import { ContactForm } from './ContactForm' // We'll create this file next


function Root() {
  const [showContactForm, setShowContactForm] = useState(false);

  return (
    <>
      <App />
      <div style={{ position: 'absolute', pointerEvents: 'none', top: 0, left: 0, width: '100vw', height: '100vh' }}>
        <div id="Socialsdescr" style={{height: '10px', width: '10px'}}>
          <a href="https://www.instagram.com/_skrumcious_/" target="_blank" style={{ position: 'absolute', bottom: 40, left: 90, fontSize: '13px' }}>
            Rory Henderson
            <br />
            Multimedia Designer
          </a>
        </div>
        <a 
          id="contact" 
          onClick={() => setShowContactForm(true)}
          style={{ 
            position: 'absolute', 
            bottom: 40, 
            right: 40, 
            fontSize: '13px',
            cursor: 'pointer',
            pointerEvents: 'auto' // Enable clicking
          }}
        >
          Contact
        </a>
        
        <a style={{ position: 'absolute', top: 40, left: 40, fontSize: '13px', pointerEvents: 'none'}} href="#">
          scroll up/down ...
        </a>

        <a 
         id="bio"
         style={{ position: 'absolute', top: 40, right: 40, fontSize: '13px', pointerEvents: 'auto', cursor: 'pointer'}}>
          bio
        </a>
      </div>
      {showContactForm && <ContactForm onClose={() => setShowContactForm(false)} />}
    </>
  )
}

/*
Model JSX auto-generated by: https://github.com/pmndrs/gltfjsx  
Command: npx gltfjsx@6.2.3 model.glb --transform --simplify --resolution=2048
Author: Omar Faruq Tawsif (https://sketchfab.com/omarfaruqtawsif32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
*/

createRoot(document.getElementById('root')).render(<Root />)
